---
name: Desk Sensors
description: "Placed under the main desk"
fields:
  - Manual:
      name: temperature
      length: 13
      decode_scale: 0.009999999776482582
      decode_add: -20.0
  - Manual:
      name: humidity
      length: 14
      decode_scale: 0.00800000037997961
      decode_add: 0.0
  - Manual:
      name: pressure
      length: 19
      decode_scale: 0.18000000715255738
      decode_add: 30000.0